### ISSUE TITLE
project intent, path taken, why is it cool

### ISSUE THREAD

**Issue by epogrebnyak** [k0al4/sec#1]
SEC discloses (what type of accounting reports, where to read about that). For my research I wrote a utility that help to download and parse (such and such form). Given this data I can (sol e dome research ptoblem, show a gsp, generalise dome conclusion for arbitrary firm, something else). 

My idea of new user friendly text that should attract to the project.

**Comment by k0al4** [comment]
Incorporating some of the ideas. Thanks!
